// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct BackupRuleDetail: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Backup Rule Name.
  public var ruleName: Swift.String? = nil

  /// Backup Retention in Days.
  public var retentionDays: Swift.Int32? = nil

  /// Recurrence Type. For Eg. “Weekly”,” Monthly” or “Daily”.
  public var recurrence: Swift.String? = nil

  /// Recurrence Repeat Schedule. For Eg. “1st and 25th day of the month.”
  public var recurrenceSchedule: Swift.String? = nil

  /// Backup Window For Eg. “00:00 to 06:00”
  public var backupWindow: Swift.String? = nil

  /// Backup Window Timezone in IANA format. For Eg. “America/Los_Angeles”
  public var backupWindowTimezone: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupRuleDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupRuleDetail().with { $0.ruleName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ruleName = CodingKeys(stringValue: "ruleName")
    static let retentionDays = CodingKeys(stringValue: "retentionDays")
    static let recurrence = CodingKeys(stringValue: "recurrence")
    static let recurrenceSchedule = CodingKeys(stringValue: "recurrenceSchedule")
    static let backupWindow = CodingKeys(stringValue: "backupWindow")
    static let backupWindowTimezone = CodingKeys(stringValue: "backupWindowTimezone")

    static let _knownKeys: Set<Swift.String> = [
      "ruleName",
      "retentionDays",
      "recurrence",
      "recurrenceSchedule",
      "backupWindow",
      "backupWindowTimezone",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.ruleName = try container.decodeIfPresent(Swift.String.self, forKey: .ruleName)
    self.retentionDays = try container.decodeIfPresent(Swift.Int32.self, forKey: .retentionDays)
    self.recurrence = try container.decodeIfPresent(Swift.String.self, forKey: .recurrence)
    self.recurrenceSchedule = try container.decodeIfPresent(
      Swift.String.self, forKey: .recurrenceSchedule)
    self.backupWindow = try container.decodeIfPresent(Swift.String.self, forKey: .backupWindow)
    self.backupWindowTimezone = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupWindowTimezone)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.ruleName, forKey: .ruleName)
    try container.encodeIfPresent(self.retentionDays, forKey: .retentionDays)
    try container.encodeIfPresent(self.recurrence, forKey: .recurrence)
    try container.encodeIfPresent(self.recurrenceSchedule, forKey: .recurrenceSchedule)
    try container.encodeIfPresent(self.backupWindow, forKey: .backupWindow)
    try container.encodeIfPresent(self.backupWindowTimezone, forKey: .backupWindowTimezone)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BackupRuleDetail"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
