// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// This is a BackupRecoveryJobReportLog published as part of GCBDR Reporting.
public struct BackupRecoveryJobReportLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The job_name field displays the name of the job being reported.
  public var jobName: Swift.String = Swift.String()

  /// The job_name field displays the category of the job whether it is Backup or
  /// Recovery Job.
  public var jobCategory: Swift.String = Swift.String()

  /// The job_type field displays the type of the job.
  public var jobType: Swift.String = Swift.String()

  /// The log_backup field displays whether the backup taken is only for logs, DB
  /// or both.
  public var logBackup: Swift.String = Swift.String()

  /// The job_status field displays the status of the job.
  public var jobStatus: Swift.String = Swift.String()

  /// The resource_name field displays the name of the resource.
  public var resourceName: Swift.String = Swift.String()

  /// The resource_type field displays the type of the resource.
  public var resourceType: Swift.String = Swift.String()

  /// The error_code field displays the error code.
  public var errorCode: Swift.Int32 = Swift.Int32()

  /// The error_message field displays the error message if the job is not
  /// successful.
  public var errorMessage: Swift.String = Swift.String()

  /// The job_initiation_failure_reason field displays the reason for failure,
  /// if the job was not run.
  public var jobInitiationFailureReason: Swift.String = Swift.String()

  /// The job_start_time field displays the timestamp when the job started.
  public var jobStartTime: Swift.String = Swift.String()

  /// The job_end_time field displays the timestamp when the job ended.
  public var jobEndTime: Swift.String = Swift.String()

  /// The job_queued_time field displays the timestamp when the job was
  /// queued for running.
  public var jobQueuedTime: Swift.String = Swift.String()

  /// The job_duration_in_hours field displays the duration in hours which the
  /// job took to complete.
  public var jobDurationInHours: Swift.Double = Swift.Double()

  /// The hostname field displays the name of the host.
  public var hostname: Swift.String = Swift.String()

  /// The appliance_name field displays the name of the backup appliance.
  public var applianceName: Swift.String = Swift.String()

  /// The backup_rule_policy_name field displays the policy name which is
  /// associated with this job.
  public var backupRulePolicyName: Swift.String = Swift.String()

  /// The backup_plan_policy_template field displays the name of the backup plan
  /// for this application.
  public var backupPlanPolicyTemplate: Swift.String = Swift.String()

  /// The backup_type field displays the type of backup taken: Log, Incremental
  /// or Full Copy.
  public var backupType: Swift.String = Swift.String()

  /// The recovery_point field displays the timestamp of recovery point.
  public var recoveryPoint: Swift.String = Swift.String()

  /// The backup_consistency field displays whether the backup is crash
  /// consistent or application consistent.
  public var backupConsistency: Swift.String = Swift.String()

  /// The target_host_name field displays the target host name.
  public var targetHostName: Swift.String = Swift.String()

  /// The target_appliance_name field displays the target appliance name.
  public var targetApplianceName: Swift.String = Swift.String()

  /// The target_pool_name field displays target pool name.
  public var targetPoolName: Swift.String = Swift.String()

  /// The resource_data_size_in_gib field displays resource data size in Gib.
  public var resourceDataSizeInGib: Swift.Double = Swift.Double()

  /// The data_copied_in_gib field displays the amount of the data copied
  /// during backup in Gib.
  public var dataCopiedInGib: Swift.Double = Swift.Double()

  /// The onvault_pool_storage_consumed_in_gib field displays the amount of
  /// onvault pool storage consumed in Gib.
  public var onvaultPoolStorageConsumedInGib: Swift.Double = Swift.Double()

  /// The pre_compress_in_gib field displays the size before compression in Gib.
  public var preCompressInGib: Swift.Double = Swift.Double()

  /// The compression_ratio field displays the ratio of post compression size to
  /// pre compression size.
  public var compressionRatio: Swift.Double = Swift.Double()

  /// The data_change_rate field displays the percentage of data copied during
  /// backup to application size.
  public var dataChangeRate: Swift.Double = Swift.Double()

  /// The snapshot_disk_size_in_gib field displays the snapshot disk size in Gib.
  public var snapshotDiskSizeInGib: Swift.Double = Swift.Double()

  /// The data_written_in_gib field displays the amount of
  /// remote data written in Gib.
  public var dataWrittenInGib: Swift.Double = Swift.Double()

  /// The data_sent_in_gib field displays the amount of
  /// network data sent in Gib.
  public var dataSentInGib: Swift.Double = Swift.Double()

  /// The job_id field displays the id of the job being reported.
  public var jobId: Swift.String = Swift.String()

  /// The host_id field displays the host id.
  public var hostId: Swift.String = Swift.String()

  /// The backup_rule_policy_id field displays the policy id.
  public var backupRulePolicyId: Swift.String = Swift.String()

  /// The resource_id field displays the resource id.
  public var resourceId: Swift.String = Swift.String()

  /// The target_pool_id field displays the target pool id.
  public var targetPoolId: Swift.String = Swift.String()

  /// The target_host_id field displays the target host id.
  public var targetHostId: Swift.String = Swift.String()

  /// The target_appliance_id field displays the target appliance id.
  public var targetApplianceId: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupRecoveryJobReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupRecoveryJobReportLog().with { $0.jobName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BackupRecoveryJobReportLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
