// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This is a BackupStorageUtilizationReportLog published as part of GCBDR
/// Reporting.
public struct BackupStorageUtilizationReportLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The appliance name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. The storage resource type.
  public var storageType: Swift.String = Swift.String()

  /// Required. The storage pool name.
  public var poolName: Swift.String = Swift.String()

  /// Required. Total capacity of the pool in GiB.
  public var totalCapacityInGib: Swift.Double = Swift.Double()

  /// Required. Used capacity of the pool in GiB.
  public var usedCapacityInGib: Swift.Double = Swift.Double()

  /// Required. Utilization percentage of a storage pool.
  public var utilizationPercentage: Swift.Double = Swift.Double()

  /// Required. Appliance id.
  public var applianceId: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupStorageUtilizationReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupStorageUtilizationReportLog().with { $0.applianceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BackupStorageUtilizationReportLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
