// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct BackupRuleDetail: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Backup Rule Name.
  public var ruleName: Swift.String? = nil

  /// Backup Retention in Days.
  public var retentionDays: Swift.Int32? = nil

  /// Recurrence Type. For Eg. “Weekly”,” Monthly” or “Daily”.
  public var recurrence: Swift.String? = nil

  /// Recurrence Repeat Schedule. For Eg. “1st and 25th day of the month.”
  public var recurrenceSchedule: Swift.String? = nil

  /// Backup Window For Eg. “00:00 to 06:00”
  public var backupWindow: Swift.String? = nil

  /// Backup Window Timezone in IANA format. For Eg. “America/Los_Angeles”
  public var backupWindowTimezone: Swift.String? = nil

  /// Initialize a new instance of `BackupRuleDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupRuleDetail().with { $0.ruleName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BackupRuleDetail"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
