// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// This is a BackupStorageUtilizationReportLog published as part of GCBDR
/// Reporting.
public struct BackupStorageUtilizationReportLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The appliance name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. The storage resource type.
  public var storageType: Swift.String = Swift.String()

  /// Required. The storage pool name.
  public var poolName: Swift.String = Swift.String()

  /// Required. Total capacity of the pool in GiB.
  public var totalCapacityInGib: Swift.Double = Swift.Double()

  /// Required. Used capacity of the pool in GiB.
  public var usedCapacityInGib: Swift.Double = Swift.Double()

  /// Required. Utilization percentage of a storage pool.
  public var utilizationPercentage: Swift.Double = Swift.Double()

  /// Required. Appliance id.
  public var applianceId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupStorageUtilizationReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupStorageUtilizationReportLog().with { $0.applianceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let applianceName = CodingKeys(stringValue: "applianceName")
    static let storageType = CodingKeys(stringValue: "storageType")
    static let poolName = CodingKeys(stringValue: "poolName")
    static let totalCapacityInGib = CodingKeys(stringValue: "totalCapacityInGib")
    static let usedCapacityInGib = CodingKeys(stringValue: "usedCapacityInGib")
    static let utilizationPercentage = CodingKeys(stringValue: "utilizationPercentage")
    static let applianceId = CodingKeys(stringValue: "applianceId")

    static let _knownKeys: Set<Swift.String> = [
      "applianceName",
      "storageType",
      "poolName",
      "totalCapacityInGib",
      "usedCapacityInGib",
      "utilizationPercentage",
      "applianceId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceName) {
      self.applianceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .storageType) {
      self.storageType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .poolName) {
      self.poolName = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .totalCapacityInGib) {
      self.totalCapacityInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .usedCapacityInGib) {
      self.usedCapacityInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .utilizationPercentage)
    {
      self.utilizationPercentage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceId) {
      self.applianceId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.applianceName, forKey: .applianceName)
    try container.encode(self.storageType, forKey: .storageType)
    try container.encode(self.poolName, forKey: .poolName)
    try container.encode(self.totalCapacityInGib, forKey: .totalCapacityInGib)
    try container.encode(self.usedCapacityInGib, forKey: .usedCapacityInGib)
    try container.encode(self.utilizationPercentage, forKey: .utilizationPercentage)
    try container.encode(self.applianceId, forKey: .applianceId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BackupStorageUtilizationReportLog"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
