// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Log entry for BDRBackupPlanJobLog for resources using BackupPlan
/// based protection.
public struct BDRBackupPlanJobLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The job_id field displays the identifier of the job being reported.
  public var jobId: Swift.String = Swift.String()

  /// The category field displays the category of the job. Can be one of
  /// [UPDATE_BACKUP_PLAN].
  public var jobCategory: Swift.String = Swift.String()

  /// The status field displays the status of the job. Can be one of
  /// [RUNNING,SUCCESSFUL, FAILED].
  public var jobStatus: Swift.String = Swift.String()

  /// The resource_type field displays the type of the protected resource.
  public var resourceType: Swift.String = Swift.String()

  /// Canonical resource name for Backup Plan Plan of the job.
  public var backupPlanName: Swift.String = Swift.String()

  /// User friendly revision id e.g. v0, v1 etc.
  public var previousBackupPlanRevisionId: Swift.String = Swift.String()

  /// Full resource name for previous backup plan revision
  public var previousBackupPlanRevisionName: Swift.String = Swift.String()

  /// User friendly revision id e.g. v0, v1 etc.
  public var newBackupPlanRevisionId: Swift.String = Swift.String()

  /// Full resource name for new backup plan revision
  public var newBackupPlanRevisionName: Swift.String = Swift.String()

  /// Start time of the job.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// End time of the job.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// The total number of workloads affected by the job.
  public var workloadsAffectedCount: Swift.Int32 = Swift.Int32()

  /// Previous Backup Plan rules.
  public var previousBackupRules: [BackupRuleDetail] = []

  /// Revised Backup Plan rules.
  public var revisedBackupRules: [BackupRuleDetail] = []

  /// The error code. Only populated in error scenarios.
  public var errorCode: Swift.Int32 = Swift.Int32()

  /// The name of the error type eg. PERMISSION_DENIED. Only populated in error
  /// scenarios.
  public var errorType: Swift.String = Swift.String()

  /// The user readable error message. Only populated in error scenarios.
  public var errorMessage: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BDRBackupPlanJobLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupPlanJobLog().with { $0.jobId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let jobId = CodingKeys(stringValue: "jobId")
    static let jobCategory = CodingKeys(stringValue: "jobCategory")
    static let jobStatus = CodingKeys(stringValue: "jobStatus")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let backupPlanName = CodingKeys(stringValue: "backupPlanName")
    static let previousBackupPlanRevisionId = CodingKeys(
      stringValue: "previousBackupPlanRevisionId")
    static let previousBackupPlanRevisionName = CodingKeys(
      stringValue: "previousBackupPlanRevisionName")
    static let newBackupPlanRevisionId = CodingKeys(stringValue: "newBackupPlanRevisionId")
    static let newBackupPlanRevisionName = CodingKeys(stringValue: "newBackupPlanRevisionName")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let workloadsAffectedCount = CodingKeys(stringValue: "workloadsAffectedCount")
    static let previousBackupRules = CodingKeys(stringValue: "previousBackupRules")
    static let revisedBackupRules = CodingKeys(stringValue: "revisedBackupRules")
    static let errorCode = CodingKeys(stringValue: "errorCode")
    static let errorType = CodingKeys(stringValue: "errorType")
    static let errorMessage = CodingKeys(stringValue: "errorMessage")

    static let _knownKeys: Set<Swift.String> = [
      "jobId",
      "jobCategory",
      "jobStatus",
      "resourceType",
      "backupPlanName",
      "previousBackupPlanRevisionId",
      "previousBackupPlanRevisionName",
      "newBackupPlanRevisionId",
      "newBackupPlanRevisionName",
      "startTime",
      "endTime",
      "workloadsAffectedCount",
      "previousBackupRules",
      "revisedBackupRules",
      "errorCode",
      "errorType",
      "errorMessage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobId) {
      self.jobId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobCategory) {
      self.jobCategory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobStatus) {
      self.jobStatus = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupPlanName) {
      self.backupPlanName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .previousBackupPlanRevisionId)
    {
      self.previousBackupPlanRevisionId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .previousBackupPlanRevisionName)
    {
      self.previousBackupPlanRevisionName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .newBackupPlanRevisionId)
    {
      self.newBackupPlanRevisionId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .newBackupPlanRevisionName)
    {
      self.newBackupPlanRevisionName = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .workloadsAffectedCount)
    {
      self.workloadsAffectedCount = value
    }
    if let value = try container.decodeIfPresent(
      [BackupRuleDetail].self, forKey: .previousBackupRules)
    {
      self.previousBackupRules = value
    }
    if let value = try container.decodeIfPresent(
      [BackupRuleDetail].self, forKey: .revisedBackupRules)
    {
      self.revisedBackupRules = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .errorCode) {
      self.errorCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorType) {
      self.errorType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
      self.errorMessage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.jobId, forKey: .jobId)
    try container.encode(self.jobCategory, forKey: .jobCategory)
    try container.encode(self.jobStatus, forKey: .jobStatus)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.backupPlanName, forKey: .backupPlanName)
    try container.encode(self.previousBackupPlanRevisionId, forKey: .previousBackupPlanRevisionId)
    try container.encode(
      self.previousBackupPlanRevisionName, forKey: .previousBackupPlanRevisionName)
    try container.encode(self.newBackupPlanRevisionId, forKey: .newBackupPlanRevisionId)
    try container.encode(self.newBackupPlanRevisionName, forKey: .newBackupPlanRevisionName)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.workloadsAffectedCount, forKey: .workloadsAffectedCount)
    try container.encode(self.previousBackupRules, forKey: .previousBackupRules)
    try container.encode(self.revisedBackupRules, forKey: .revisedBackupRules)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.errorType, forKey: .errorType)
    try container.encode(self.errorMessage, forKey: .errorMessage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupPlanJobLog"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
