// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Log entry for BDRBackupPlanAssociationJobLog for resources using BackupPlan
/// based protection.
public struct BDRBackupPlanAssociationJobLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The job_id field displays the identifier of the job being reported.
  public var jobId: Swift.String? = nil

  /// The category field displays the category of the job. Can be one of
  /// [UPDATE].
  public var jobCategory: Swift.String? = nil

  /// The status field displays the status of the job. Can be one of [RUNNING,
  /// QUEUED, SUCCESSFUL, FAILED, SKIPPED].
  public var jobStatus: Swift.String? = nil

  /// Full resource name of the protected resource.
  public var sourceResourceName: Swift.String? = nil

  /// resource id of the protected resource.
  public var sourceResourceId: Swift.String? = nil

  /// resource location of the protected resource.
  public var sourceResourceLocation: Swift.String? = nil

  /// The resource_type field displays the type of the protected resource.
  public var resourceType: Swift.String? = nil

  /// Full resource name for Backup Plan Association of the job.
  public var backupPlanAssociationName: Swift.String? = nil

  /// Full resource name for previous Backup Plan of the job. Populated for
  /// Update BPA.
  public var previousBackupPlanName: Swift.String? = nil

  /// User friendly revision id e.g. v0, v1 etc.
  public var previousBackupPlanRevisionId: Swift.String? = nil

  /// Full resource name for previous backup plan revision
  public var previousBackupPlanRevisionName: Swift.String? = nil

  /// Full resource name for new Backup Plan. Populated for Update & Create BPA.
  public var newBackupPlanName: Swift.String? = nil

  /// User friendly revision id e.g. v0, v1 etc.
  public var newBackupPlanRevisionId: Swift.String? = nil

  /// Full resource name for new backup plan revision
  public var newBackupPlanRevisionName: Swift.String? = nil

  /// Start time of the job.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// End time of the job.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// The error code. Only populated in error scenarios.
  public var errorCode: Swift.Int32? = nil

  /// The name of the error type eg. PERMISSION_DENIED. Only populated in error
  /// scenarios.
  public var errorType: Swift.String? = nil

  /// The user readable error message. Only populated in error scenarios.
  public var errorMessage: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BDRBackupPlanAssociationJobLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupPlanAssociationJobLog().with { $0.jobId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let jobId = CodingKeys(stringValue: "jobId")
    static let jobCategory = CodingKeys(stringValue: "jobCategory")
    static let jobStatus = CodingKeys(stringValue: "jobStatus")
    static let sourceResourceName = CodingKeys(stringValue: "sourceResourceName")
    static let sourceResourceId = CodingKeys(stringValue: "sourceResourceId")
    static let sourceResourceLocation = CodingKeys(stringValue: "sourceResourceLocation")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let backupPlanAssociationName = CodingKeys(stringValue: "backupPlanAssociationName")
    static let previousBackupPlanName = CodingKeys(stringValue: "previousBackupPlanName")
    static let previousBackupPlanRevisionId = CodingKeys(
      stringValue: "previousBackupPlanRevisionId")
    static let previousBackupPlanRevisionName = CodingKeys(
      stringValue: "previousBackupPlanRevisionName")
    static let newBackupPlanName = CodingKeys(stringValue: "newBackupPlanName")
    static let newBackupPlanRevisionId = CodingKeys(stringValue: "newBackupPlanRevisionId")
    static let newBackupPlanRevisionName = CodingKeys(stringValue: "newBackupPlanRevisionName")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let errorCode = CodingKeys(stringValue: "errorCode")
    static let errorType = CodingKeys(stringValue: "errorType")
    static let errorMessage = CodingKeys(stringValue: "errorMessage")

    static let _knownKeys: Set<Swift.String> = [
      "jobId",
      "jobCategory",
      "jobStatus",
      "sourceResourceName",
      "sourceResourceId",
      "sourceResourceLocation",
      "resourceType",
      "backupPlanAssociationName",
      "previousBackupPlanName",
      "previousBackupPlanRevisionId",
      "previousBackupPlanRevisionName",
      "newBackupPlanName",
      "newBackupPlanRevisionId",
      "newBackupPlanRevisionName",
      "startTime",
      "endTime",
      "errorCode",
      "errorType",
      "errorMessage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.jobId = try container.decodeIfPresent(Swift.String.self, forKey: .jobId)
    self.jobCategory = try container.decodeIfPresent(Swift.String.self, forKey: .jobCategory)
    self.jobStatus = try container.decodeIfPresent(Swift.String.self, forKey: .jobStatus)
    self.sourceResourceName = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceName)
    self.sourceResourceId = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceId)
    self.sourceResourceLocation = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceLocation)
    self.resourceType = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType)
    self.backupPlanAssociationName = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupPlanAssociationName)
    self.previousBackupPlanName = try container.decodeIfPresent(
      Swift.String.self, forKey: .previousBackupPlanName)
    self.previousBackupPlanRevisionId = try container.decodeIfPresent(
      Swift.String.self, forKey: .previousBackupPlanRevisionId)
    self.previousBackupPlanRevisionName = try container.decodeIfPresent(
      Swift.String.self, forKey: .previousBackupPlanRevisionName)
    self.newBackupPlanName = try container.decodeIfPresent(
      Swift.String.self, forKey: .newBackupPlanName)
    self.newBackupPlanRevisionId = try container.decodeIfPresent(
      Swift.String.self, forKey: .newBackupPlanRevisionId)
    self.newBackupPlanRevisionName = try container.decodeIfPresent(
      Swift.String.self, forKey: .newBackupPlanRevisionName)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWKT.Timestamp.self, forKey: .endTime)
    self.errorCode = try container.decodeIfPresent(Swift.Int32.self, forKey: .errorCode)
    self.errorType = try container.decodeIfPresent(Swift.String.self, forKey: .errorType)
    self.errorMessage = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.jobId, forKey: .jobId)
    try container.encodeIfPresent(self.jobCategory, forKey: .jobCategory)
    try container.encodeIfPresent(self.jobStatus, forKey: .jobStatus)
    try container.encodeIfPresent(self.sourceResourceName, forKey: .sourceResourceName)
    try container.encodeIfPresent(self.sourceResourceId, forKey: .sourceResourceId)
    try container.encodeIfPresent(self.sourceResourceLocation, forKey: .sourceResourceLocation)
    try container.encodeIfPresent(self.resourceType, forKey: .resourceType)
    try container.encodeIfPresent(
      self.backupPlanAssociationName, forKey: .backupPlanAssociationName)
    try container.encodeIfPresent(self.previousBackupPlanName, forKey: .previousBackupPlanName)
    try container.encodeIfPresent(
      self.previousBackupPlanRevisionId, forKey: .previousBackupPlanRevisionId)
    try container.encodeIfPresent(
      self.previousBackupPlanRevisionName, forKey: .previousBackupPlanRevisionName)
    try container.encodeIfPresent(self.newBackupPlanName, forKey: .newBackupPlanName)
    try container.encodeIfPresent(self.newBackupPlanRevisionId, forKey: .newBackupPlanRevisionId)
    try container.encodeIfPresent(
      self.newBackupPlanRevisionName, forKey: .newBackupPlanRevisionName)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encodeIfPresent(self.errorCode, forKey: .errorCode)
    try container.encodeIfPresent(self.errorType, forKey: .errorType)
    try container.encodeIfPresent(self.errorMessage, forKey: .errorMessage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupPlanAssociationJobLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
