// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Log entry for BDRBackupPlanAssociationJobLog for resources using BackupPlan
/// based protection.
public struct BDRBackupPlanAssociationJobLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The job_id field displays the identifier of the job being reported.
  public var jobId: Swift.String? = nil

  /// The category field displays the category of the job. Can be one of
  /// [UPDATE].
  public var jobCategory: Swift.String? = nil

  /// The status field displays the status of the job. Can be one of [RUNNING,
  /// QUEUED, SUCCESSFUL, FAILED, SKIPPED].
  public var jobStatus: Swift.String? = nil

  /// Full resource name of the protected resource.
  public var sourceResourceName: Swift.String? = nil

  /// resource id of the protected resource.
  public var sourceResourceId: Swift.String? = nil

  /// resource location of the protected resource.
  public var sourceResourceLocation: Swift.String? = nil

  /// The resource_type field displays the type of the protected resource.
  public var resourceType: Swift.String? = nil

  /// Full resource name for Backup Plan Association of the job.
  public var backupPlanAssociationName: Swift.String? = nil

  /// Full resource name for previous Backup Plan of the job. Populated for
  /// Update BPA.
  public var previousBackupPlanName: Swift.String? = nil

  /// User friendly revision id e.g. v0, v1 etc.
  public var previousBackupPlanRevisionId: Swift.String? = nil

  /// Full resource name for previous backup plan revision
  public var previousBackupPlanRevisionName: Swift.String? = nil

  /// Full resource name for new Backup Plan. Populated for Update & Create BPA.
  public var newBackupPlanName: Swift.String? = nil

  /// User friendly revision id e.g. v0, v1 etc.
  public var newBackupPlanRevisionId: Swift.String? = nil

  /// Full resource name for new backup plan revision
  public var newBackupPlanRevisionName: Swift.String? = nil

  /// Start time of the job.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// End time of the job.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// The error code. Only populated in error scenarios.
  public var errorCode: Swift.Int32? = nil

  /// The name of the error type eg. PERMISSION_DENIED. Only populated in error
  /// scenarios.
  public var errorType: Swift.String? = nil

  /// The user readable error message. Only populated in error scenarios.
  public var errorMessage: Swift.String? = nil

  /// Initialize a new instance of `BDRBackupPlanAssociationJobLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupPlanAssociationJobLog().with { $0.jobId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupPlanAssociationJobLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
