// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Log entry for BDRBackupVaultDetails Log for resources using BackupPlan based
/// protection.
public struct BDRBackupVaultDetailsLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Relative resource name of Backup Vault
  public var backupVaultName: Swift.String? = nil

  /// Relative source resource name
  public var sourceResourceName: Swift.String? = nil

  /// Type of the resource For eg. “Compute Engine”
  public var resourceType: Swift.String? = nil

  /// The name of the Backup Plan applied on the resource to protect.
  public var currentBackupPlanName: Swift.String? = nil

  /// Timestamp when the first (oldest) backup was taken.
  public var firstAvailableRestorePoint: GoogleWKT.Timestamp? = nil

  /// Timestamp when the latest backup was taken.
  public var lastAvailableRestorePoint: GoogleWKT.Timestamp? = nil

  /// Amount of storage space consumed by backups in GiB.
  public var storedBytesGib: Swift.Double? = nil

  /// The minimum timeframe in days that backups in that vault are being
  /// protected from deletion.
  public var minimumEnforcedRetentionDays: Swift.Int32? = nil

  /// Source resource_location
  public var sourceResourceLocation: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BDRBackupVaultDetailsLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupVaultDetailsLog().with { $0.backupVaultName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupVaultName = CodingKeys(stringValue: "backupVaultName")
    static let sourceResourceName = CodingKeys(stringValue: "sourceResourceName")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let currentBackupPlanName = CodingKeys(stringValue: "currentBackupPlanName")
    static let firstAvailableRestorePoint = CodingKeys(stringValue: "firstAvailableRestorePoint")
    static let lastAvailableRestorePoint = CodingKeys(stringValue: "lastAvailableRestorePoint")
    static let storedBytesGib = CodingKeys(stringValue: "storedBytesGib")
    static let minimumEnforcedRetentionDays = CodingKeys(
      stringValue: "minimumEnforcedRetentionDays")
    static let sourceResourceLocation = CodingKeys(stringValue: "sourceResourceLocation")

    static let _knownKeys: Set<Swift.String> = [
      "backupVaultName",
      "sourceResourceName",
      "resourceType",
      "currentBackupPlanName",
      "firstAvailableRestorePoint",
      "lastAvailableRestorePoint",
      "storedBytesGib",
      "minimumEnforcedRetentionDays",
      "sourceResourceLocation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.backupVaultName = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupVaultName)
    self.sourceResourceName = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceName)
    self.resourceType = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType)
    self.currentBackupPlanName = try container.decodeIfPresent(
      Swift.String.self, forKey: .currentBackupPlanName)
    self.firstAvailableRestorePoint = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .firstAvailableRestorePoint)
    self.lastAvailableRestorePoint = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastAvailableRestorePoint)
    self.storedBytesGib = try container.decodeIfPresent(Swift.Double.self, forKey: .storedBytesGib)
    self.minimumEnforcedRetentionDays = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .minimumEnforcedRetentionDays)
    self.sourceResourceLocation = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceLocation)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.backupVaultName, forKey: .backupVaultName)
    try container.encodeIfPresent(self.sourceResourceName, forKey: .sourceResourceName)
    try container.encodeIfPresent(self.resourceType, forKey: .resourceType)
    try container.encodeIfPresent(self.currentBackupPlanName, forKey: .currentBackupPlanName)
    try container.encodeIfPresent(
      self.firstAvailableRestorePoint, forKey: .firstAvailableRestorePoint)
    try container.encodeIfPresent(
      self.lastAvailableRestorePoint, forKey: .lastAvailableRestorePoint)
    try container.encodeIfPresent(self.storedBytesGib, forKey: .storedBytesGib)
    try container.encodeIfPresent(
      self.minimumEnforcedRetentionDays, forKey: .minimumEnforcedRetentionDays)
    try container.encodeIfPresent(self.sourceResourceLocation, forKey: .sourceResourceLocation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupVaultDetailsLog"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
