// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Log entry for Backup and Restore Job for resources using BackupPlan based
/// protection.
public struct BDRBackupRestoreJobLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The job_id field displays the identifier of the job being logged.
  public var jobId: Swift.String? = nil

  /// The category field displays the category of the job.
  public var jobCategory: Swift.String? = nil

  /// The status field displays the status of the job.
  public var jobStatus: Swift.String? = nil

  /// Full resource name of the protected resource.
  public var sourceResourceName: Swift.String? = nil

  /// The source resource ID.
  public var sourceResourceId: Swift.String? = nil

  /// Full resource name of the restore resource. Only populated in
  /// restore jobs.
  public var restoreResourceName: Swift.String? = nil

  /// Full resource name of the backup created in backup jobs and used in restore
  /// jobs.
  public var backupName: Swift.String? = nil

  /// The resource_type field displays the type of the protected resource.
  public var resourceType: Swift.String? = nil

  /// Start time of the job.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// End time of the job.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Full resource name for Backup Plan of the job. Only populated for Scheduled
  /// Backup and Adhoc Backup.
  public var backupPlanName: Swift.String? = nil

  /// Name of the backup rule. Only populated for Scheduled Backup and Adhoc
  /// Backup.
  public var backupRule: Swift.String? = nil

  /// Backup retention in days.
  public var backupRetentionDays: Swift.Int32? = nil

  /// Full resource name backup vault name
  public var backupVaultName: Swift.String? = nil

  /// The amount of incremental backup data copied.
  public var incrementalBackupSizeGib: Swift.Double? = nil

  /// The error code. Only populated in error scenarios.
  public var errorCode: Swift.Int32? = nil

  /// The name of the error type eg. PERMISSION_DENIED. Only populated in error
  /// scenarios.
  public var errorType: Swift.String? = nil

  /// The user readable error message. Only populated in error scenarios.
  public var errorMessage: Swift.String? = nil

  /// Backup consistency time.
  public var backupConsistencyTime: GoogleCloudWkt.Timestamp? = nil

  /// Source resource location.
  public var sourceResourceLocation: Swift.String? = nil

  /// Restore resource location.
  public var restoreResourceLocation: Swift.String? = nil

  /// Initialize a new instance of `BDRBackupRestoreJobLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupRestoreJobLog().with { $0.jobId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupRestoreJobLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
