// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Log entry for BDRBackupPlanJobLog for resources using BackupPlan
/// based protection.
public struct BDRBackupPlanJobLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The job_id field displays the identifier of the job being reported.
  public var jobId: Swift.String = Swift.String()

  /// The category field displays the category of the job. Can be one of
  /// [UPDATE_BACKUP_PLAN].
  public var jobCategory: Swift.String = Swift.String()

  /// The status field displays the status of the job. Can be one of
  /// [RUNNING,SUCCESSFUL, FAILED].
  public var jobStatus: Swift.String = Swift.String()

  /// The resource_type field displays the type of the protected resource.
  public var resourceType: Swift.String = Swift.String()

  /// Canonical resource name for Backup Plan Plan of the job.
  public var backupPlanName: Swift.String = Swift.String()

  /// User friendly revision id e.g. v0, v1 etc.
  public var previousBackupPlanRevisionId: Swift.String = Swift.String()

  /// Full resource name for previous backup plan revision
  public var previousBackupPlanRevisionName: Swift.String = Swift.String()

  /// User friendly revision id e.g. v0, v1 etc.
  public var newBackupPlanRevisionId: Swift.String = Swift.String()

  /// Full resource name for new backup plan revision
  public var newBackupPlanRevisionName: Swift.String = Swift.String()

  /// Start time of the job.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// End time of the job.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// The total number of workloads affected by the job.
  public var workloadsAffectedCount: Swift.Int32 = Swift.Int32()

  /// Previous Backup Plan rules.
  public var previousBackupRules: [BackupRuleDetail] = []

  /// Revised Backup Plan rules.
  public var revisedBackupRules: [BackupRuleDetail] = []

  /// The error code. Only populated in error scenarios.
  public var errorCode: Swift.Int32 = Swift.Int32()

  /// The name of the error type eg. PERMISSION_DENIED. Only populated in error
  /// scenarios.
  public var errorType: Swift.String = Swift.String()

  /// The user readable error message. Only populated in error scenarios.
  public var errorMessage: Swift.String = Swift.String()

  /// Initialize a new instance of `BDRBackupPlanJobLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupPlanJobLog().with { $0.jobId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupPlanJobLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
