// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Log entry for BDRBackupVaultDetails Log for resources using BackupPlan based
/// protection.
public struct BDRBackupVaultDetailsLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Relative resource name of Backup Vault
  public var backupVaultName: Swift.String? = nil

  /// Relative source resource name
  public var sourceResourceName: Swift.String? = nil

  /// Type of the resource For eg. “Compute Engine”
  public var resourceType: Swift.String? = nil

  /// The name of the Backup Plan applied on the resource to protect.
  public var currentBackupPlanName: Swift.String? = nil

  /// Timestamp when the first (oldest) backup was taken.
  public var firstAvailableRestorePoint: GoogleCloudWKT.Timestamp? = nil

  /// Timestamp when the latest backup was taken.
  public var lastAvailableRestorePoint: GoogleCloudWKT.Timestamp? = nil

  /// Amount of storage space consumed by backups in GiB.
  public var storedBytesGib: Swift.Double? = nil

  /// The minimum timeframe in days that backups in that vault are being
  /// protected from deletion.
  public var minimumEnforcedRetentionDays: Swift.Int32? = nil

  /// Source resource_location
  public var sourceResourceLocation: Swift.String? = nil

  /// Initialize a new instance of `BDRBackupVaultDetailsLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRBackupVaultDetailsLog().with { $0.backupVaultName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRBackupVaultDetailsLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
