// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Log entry for BDRProtectedResource Log for resources using BackupPlan based
/// protection.
public struct BDRProtectedResourceLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Full canonical source resource name.
  public var sourceResourceName: Swift.String? = nil

  /// The source resource ID. Instance Id for GCE.
  public var sourceResourceId: Swift.String? = nil

  /// Type of the resource. For eg. “Compute Engine”.
  public var resourceType: Swift.String? = nil

  /// The size of the protected source resource in GiB, rounded to 2 decimal
  /// places.
  public var sourceResourceDataSizeGib: Swift.Double? = nil

  /// Complete canonical name of the Backup plan currently associated with the
  /// source resource.
  public var currentBackupPlanName: Swift.String? = nil

  /// Backup Rule details of the backup plan currently associated with the source
  /// resource.
  public var currentBackupRuleDetails: [BackupRuleDetail] = []

  /// Timestamp when the resource was last protected.
  public var lastProtectedOn: GoogleWKT.WKTTimestamp? = nil

  /// Full Resource Name of the backup vault currently associated with the source
  /// resource.
  public var currentBackupVaultName: Swift.String? = nil

  /// Source resource_location
  public var sourceResourceLocation: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BDRProtectedResourceLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRProtectedResourceLog().with { $0.sourceResourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceResourceName = CodingKeys(stringValue: "sourceResourceName")
    static let sourceResourceId = CodingKeys(stringValue: "sourceResourceId")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let sourceResourceDataSizeGib = CodingKeys(stringValue: "sourceResourceDataSizeGib")
    static let currentBackupPlanName = CodingKeys(stringValue: "currentBackupPlanName")
    static let currentBackupRuleDetails = CodingKeys(stringValue: "currentBackupRuleDetails")
    static let lastProtectedOn = CodingKeys(stringValue: "lastProtectedOn")
    static let currentBackupVaultName = CodingKeys(stringValue: "currentBackupVaultName")
    static let sourceResourceLocation = CodingKeys(stringValue: "sourceResourceLocation")

    static let _knownKeys: Set<Swift.String> = [
      "sourceResourceName",
      "sourceResourceId",
      "resourceType",
      "sourceResourceDataSizeGib",
      "currentBackupPlanName",
      "currentBackupRuleDetails",
      "lastProtectedOn",
      "currentBackupVaultName",
      "sourceResourceLocation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.sourceResourceName = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceName)
    self.sourceResourceId = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceId)
    self.resourceType = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType)
    self.sourceResourceDataSizeGib = try container.decodeIfPresent(
      Swift.Double.self, forKey: .sourceResourceDataSizeGib)
    self.currentBackupPlanName = try container.decodeIfPresent(
      Swift.String.self, forKey: .currentBackupPlanName)
    if let value = try container.decodeIfPresent(
      [BackupRuleDetail].self, forKey: .currentBackupRuleDetails)
    {
      self.currentBackupRuleDetails = value
    }
    self.lastProtectedOn = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastProtectedOn)
    self.currentBackupVaultName = try container.decodeIfPresent(
      Swift.String.self, forKey: .currentBackupVaultName)
    self.sourceResourceLocation = try container.decodeIfPresent(
      Swift.String.self, forKey: .sourceResourceLocation)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.sourceResourceName, forKey: .sourceResourceName)
    try container.encodeIfPresent(self.sourceResourceId, forKey: .sourceResourceId)
    try container.encodeIfPresent(self.resourceType, forKey: .resourceType)
    try container.encodeIfPresent(
      self.sourceResourceDataSizeGib, forKey: .sourceResourceDataSizeGib)
    try container.encodeIfPresent(self.currentBackupPlanName, forKey: .currentBackupPlanName)
    try container.encode(self.currentBackupRuleDetails, forKey: .currentBackupRuleDetails)
    try container.encodeIfPresent(self.lastProtectedOn, forKey: .lastProtectedOn)
    try container.encodeIfPresent(self.currentBackupVaultName, forKey: .currentBackupVaultName)
    try container.encodeIfPresent(self.sourceResourceLocation, forKey: .sourceResourceLocation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRProtectedResourceLog"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
