// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Log entry for BDRProtectedResource Log for resources using BackupPlan based
/// protection.
public struct BDRProtectedResourceLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Full canonical source resource name.
  public var sourceResourceName: Swift.String? = nil

  /// The source resource ID. Instance Id for GCE.
  public var sourceResourceId: Swift.String? = nil

  /// Type of the resource. For eg. “Compute Engine”.
  public var resourceType: Swift.String? = nil

  /// The size of the protected source resource in GiB, rounded to 2 decimal
  /// places.
  public var sourceResourceDataSizeGib: Swift.Double? = nil

  /// Complete canonical name of the Backup plan currently associated with the
  /// source resource.
  public var currentBackupPlanName: Swift.String? = nil

  /// Backup Rule details of the backup plan currently associated with the source
  /// resource.
  public var currentBackupRuleDetails: [BackupRuleDetail] = []

  /// Timestamp when the resource was last protected.
  public var lastProtectedOn: GoogleCloudWKT.Timestamp? = nil

  /// Full Resource Name of the backup vault currently associated with the source
  /// resource.
  public var currentBackupVaultName: Swift.String? = nil

  /// Source resource_location
  public var sourceResourceLocation: Swift.String? = nil

  /// Initialize a new instance of `BDRProtectedResourceLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BDRProtectedResourceLog().with { $0.sourceResourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.BDRProtectedResourceLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
