// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Holds information for the Connector Versions log
public struct ConnectorVersionReportLog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Appliance Name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. Appliance Id.
  public var applianceId: Swift.String = Swift.String()

  /// Required. Host Name.
  public var hostName: Swift.String = Swift.String()

  /// Required. Host Id.
  public var hostId: Swift.String = Swift.String()

  /// Optional. Os Type.
  public var hostOsType: Swift.String = Swift.String()

  /// Required. Host Ip Address.
  public var hostIpAddress: Swift.String = Swift.String()

  /// Optional. Db Authentication.
  public var dbAuthentication: Swift.String = Swift.String()

  /// Required. Installed version.
  public var installedVersion: Swift.String = Swift.String()

  /// Optional. Available version.
  public var availableVersion: Swift.String = Swift.String()

  /// Required. Version Check.
  public var versionCheck: Swift.String = Swift.String()

  /// Required. Disk Preference.
  public var diskPreference: Swift.String = Swift.String()

  /// Required. Transport
  public var transport: Swift.String = Swift.String()

  /// Initialize a new instance of `ConnectorVersionReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectorVersionReportLog().with { $0.applianceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.ConnectorVersionReportLog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
