// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This is a DailyScheduleComplianceReportLog published as part of GCBDR
/// Reporting.
public struct DailyScheduleComplianceReportLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Resource/App Name.
  public var resourceName: Swift.String = Swift.String()

  /// Required. Resource/App Type.
  public var resourceType: Swift.String = Swift.String()

  /// Required. Policy Name.
  public var backupRulePolicyName: Swift.String = Swift.String()

  /// Required. Policy Template Name.
  public var backupPlanPolicyTemplate: Swift.String = Swift.String()

  /// Required. Name of the host where the app/resource resides.
  public var hostName: Swift.String = Swift.String()

  /// Required. Appliance Name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. Date for which compliance is being reported.
  public var date: Swift.String = Swift.String()

  /// Required. Backup Window Start time.
  public var backupWindowStartTime: Swift.String = Swift.String()

  /// Required. JobType of the policy.
  public var jobType: Swift.String = Swift.String()

  /// Required. Compliance status for the policy.
  public var status: Swift.String = Swift.String()

  /// Required. Description for the status reason.
  public var comment: Swift.String = Swift.String()

  /// Required. Resource/App Id.
  public var resourceId: Swift.String = Swift.String()

  /// Required. Host Id.
  public var hostId: Swift.String = Swift.String()

  /// Required. Policy Template Id
  public var backupPlanPolicyTemplateId: Swift.String = Swift.String()

  /// Required. Policy Id.
  public var backupRulePolicyId: Swift.String = Swift.String()

  /// Required. Appliance Id.
  public var applianceId: Swift.String = Swift.String()

  /// Initialize a new instance of `DailyScheduleComplianceReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DailyScheduleComplianceReportLog().with { $0.resourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.DailyScheduleComplianceReportLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
