// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// This is a DailyScheduleComplianceReportLog published as part of GCBDR
/// Reporting.
public struct DailyScheduleComplianceReportLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Resource/App Name.
  public var resourceName: Swift.String = Swift.String()

  /// Required. Resource/App Type.
  public var resourceType: Swift.String = Swift.String()

  /// Required. Policy Name.
  public var backupRulePolicyName: Swift.String = Swift.String()

  /// Required. Policy Template Name.
  public var backupPlanPolicyTemplate: Swift.String = Swift.String()

  /// Required. Name of the host where the app/resource resides.
  public var hostName: Swift.String = Swift.String()

  /// Required. Appliance Name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. Date for which compliance is being reported.
  public var date: Swift.String = Swift.String()

  /// Required. Backup Window Start time.
  public var backupWindowStartTime: Swift.String = Swift.String()

  /// Required. JobType of the policy.
  public var jobType: Swift.String = Swift.String()

  /// Required. Compliance status for the policy.
  public var status: Swift.String = Swift.String()

  /// Required. Description for the status reason.
  public var comment: Swift.String = Swift.String()

  /// Required. Resource/App Id.
  public var resourceId: Swift.String = Swift.String()

  /// Required. Host Id.
  public var hostId: Swift.String = Swift.String()

  /// Required. Policy Template Id
  public var backupPlanPolicyTemplateId: Swift.String = Swift.String()

  /// Required. Policy Id.
  public var backupRulePolicyId: Swift.String = Swift.String()

  /// Required. Appliance Id.
  public var applianceId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DailyScheduleComplianceReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DailyScheduleComplianceReportLog().with { $0.resourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resourceName = CodingKeys(stringValue: "resourceName")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let backupRulePolicyName = CodingKeys(stringValue: "backupRulePolicyName")
    static let backupPlanPolicyTemplate = CodingKeys(stringValue: "backupPlanPolicyTemplate")
    static let hostName = CodingKeys(stringValue: "hostName")
    static let applianceName = CodingKeys(stringValue: "applianceName")
    static let date = CodingKeys(stringValue: "date")
    static let backupWindowStartTime = CodingKeys(stringValue: "backupWindowStartTime")
    static let jobType = CodingKeys(stringValue: "jobType")
    static let status = CodingKeys(stringValue: "status")
    static let comment = CodingKeys(stringValue: "comment")
    static let resourceId = CodingKeys(stringValue: "resourceId")
    static let hostId = CodingKeys(stringValue: "hostId")
    static let backupPlanPolicyTemplateId = CodingKeys(stringValue: "backupPlanPolicyTemplateId")
    static let backupRulePolicyId = CodingKeys(stringValue: "backupRulePolicyId")
    static let applianceId = CodingKeys(stringValue: "applianceId")

    static let _knownKeys: Set<Swift.String> = [
      "resourceName",
      "resourceType",
      "backupRulePolicyName",
      "backupPlanPolicyTemplate",
      "hostName",
      "applianceName",
      "date",
      "backupWindowStartTime",
      "jobType",
      "status",
      "comment",
      "resourceId",
      "hostId",
      "backupPlanPolicyTemplateId",
      "backupRulePolicyId",
      "applianceId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceName) {
      self.resourceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupRulePolicyName) {
      self.backupRulePolicyName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupPlanPolicyTemplate)
    {
      self.backupPlanPolicyTemplate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostName) {
      self.hostName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceName) {
      self.applianceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .date) {
      self.date = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupWindowStartTime)
    {
      self.backupWindowStartTime = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobType) {
      self.jobType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .status) {
      self.status = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comment) {
      self.comment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceId) {
      self.resourceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostId) {
      self.hostId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupPlanPolicyTemplateId)
    {
      self.backupPlanPolicyTemplateId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupRulePolicyId) {
      self.backupRulePolicyId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceId) {
      self.applianceId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resourceName, forKey: .resourceName)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.backupRulePolicyName, forKey: .backupRulePolicyName)
    try container.encode(self.backupPlanPolicyTemplate, forKey: .backupPlanPolicyTemplate)
    try container.encode(self.hostName, forKey: .hostName)
    try container.encode(self.applianceName, forKey: .applianceName)
    try container.encode(self.date, forKey: .date)
    try container.encode(self.backupWindowStartTime, forKey: .backupWindowStartTime)
    try container.encode(self.jobType, forKey: .jobType)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.comment, forKey: .comment)
    try container.encode(self.resourceId, forKey: .resourceId)
    try container.encode(self.hostId, forKey: .hostId)
    try container.encode(self.backupPlanPolicyTemplateId, forKey: .backupPlanPolicyTemplateId)
    try container.encode(self.backupRulePolicyId, forKey: .backupRulePolicyId)
    try container.encode(self.applianceId, forKey: .applianceId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.DailyScheduleComplianceReportLog"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
