// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This is an event
public struct Event: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The event_time field displays the time when the event was reported
  public var eventTime: Swift.String = Swift.String()

  /// The srcid field displays unique id of the event occurred in the backup
  /// appliance
  public var srcid: Swift.Int64 = Swift.Int64()

  /// The errormessage field describes the detailed error associated with the
  /// event
  public var errorMessage: Swift.String = Swift.String()

  /// The event_id field displays unique id associated with the error
  public var eventId: Swift.Int32 = Swift.Int32()

  /// The component field displays the source of the event
  public var component: Swift.String = Swift.String()

  /// The appliance_id field displays unique id of the appliance on which event
  /// occurred
  public var applianceName: Swift.Int64 = Swift.Int64()

  /// The appname field displays name of the application associated with the
  /// event
  public var appName: Swift.String = Swift.String()

  /// The apptype field displays type of the application associated with the
  /// event
  public var appType: Swift.String = Swift.String()

  /// The jobname field displays name of the job associated with the event
  public var jobName: Swift.String = Swift.String()

  /// Initialize a new instance of `Event`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Event().with { $0.eventTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.Event"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
