// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This is an event
public struct Event: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The event_time field displays the time when the event was reported
  public var eventTime: Swift.String = Swift.String()

  /// The srcid field displays unique id of the event occurred in the backup
  /// appliance
  public var srcid: Swift.Int64 = Swift.Int64()

  /// The errormessage field describes the detailed error associated with the
  /// event
  public var errorMessage: Swift.String = Swift.String()

  /// The event_id field displays unique id associated with the error
  public var eventId: Swift.Int32 = Swift.Int32()

  /// The component field displays the source of the event
  public var component: Swift.String = Swift.String()

  /// The appliance_id field displays unique id of the appliance on which event
  /// occurred
  public var applianceName: Swift.Int64 = Swift.Int64()

  /// The appname field displays name of the application associated with the
  /// event
  public var appName: Swift.String = Swift.String()

  /// The apptype field displays type of the application associated with the
  /// event
  public var appType: Swift.String = Swift.String()

  /// The jobname field displays name of the job associated with the event
  public var jobName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Event`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Event().with { $0.eventTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let eventTime = CodingKeys(stringValue: "eventTime")
    static let srcid = CodingKeys(stringValue: "srcid")
    static let errorMessage = CodingKeys(stringValue: "errorMessage")
    static let eventId = CodingKeys(stringValue: "eventId")
    static let component = CodingKeys(stringValue: "component")
    static let applianceName = CodingKeys(stringValue: "applianceName")
    static let appName = CodingKeys(stringValue: "appName")
    static let appType = CodingKeys(stringValue: "appType")
    static let jobName = CodingKeys(stringValue: "jobName")

    static let _knownKeys: Set<Swift.String> = [
      "eventTime",
      "srcid",
      "errorMessage",
      "eventId",
      "component",
      "applianceName",
      "appName",
      "appType",
      "jobName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventTime) {
      self.eventTime = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .srcid) {
      self.srcid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
      self.errorMessage = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .eventId) {
      self.eventId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .component) {
      self.component = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .applianceName) {
      self.applianceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appName) {
      self.appName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appType) {
      self.appType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobName) {
      self.jobName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.eventTime, forKey: .eventTime)
    try container.encode(self.srcid, forKey: .srcid)
    try container.encode(self.errorMessage, forKey: .errorMessage)
    try container.encode(self.eventId, forKey: .eventId)
    try container.encode(self.component, forKey: .component)
    try container.encode(self.applianceName, forKey: .applianceName)
    try container.encode(self.appName, forKey: .appName)
    try container.encode(self.appType, forKey: .appType)
    try container.encode(self.jobName, forKey: .jobName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.Event"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
