// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Holds information for the Mounted Images log
public struct MountedImage: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Source Resource name.
  public var sourceResourceName: Swift.String = Swift.String()

  /// Required. Source Resource id.
  public var sourceResourceId: Swift.String = Swift.String()

  /// Required. Cluster Name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. Cluster Id.
  public var applianceId: Swift.String = Swift.String()

  /// Required. Mounted Image Name.
  public var mountedImageName: Swift.String = Swift.String()

  /// Required. Source Image Name.
  public var sourceImageName: Swift.String = Swift.String()

  /// Required.Source Image Type.
  public var sourceImageType: Swift.String = Swift.String()

  /// Required. Recovery point Date.
  public var recoveryPointDate: Swift.String = Swift.String()

  /// Required. Last Mount Date
  public var lastMountDate: Swift.String = Swift.String()

  /// Required. Resource type.
  public var resourceType: Swift.String = Swift.String()

  /// Required. Source Host Name.
  public var sourceHostName: Swift.String = Swift.String()

  /// Required. Source Host Id.
  public var sourceHostId: Swift.String = Swift.String()

  /// Required. Mounted Host Name.
  public var mountedHostName: Swift.String = Swift.String()

  /// Required. Mounted Host Id.
  public var mountedHostId: Swift.String = Swift.String()

  /// Required. Mounted Resource Name.
  public var mountedResourceName: Swift.String = Swift.String()

  /// Required. Resource Virtual size(in GiB)
  public var resourceVirtualSizeInGib: Swift.Double = Swift.Double()

  /// Required. Storage Consumed(in GiB).
  public var storageConsumedInGib: Swift.Double = Swift.Double()

  /// Optional. label.
  public var mountedResourceLabel: Swift.String = Swift.String()

  /// Optional. Restorable Objects.
  public var restorableObject: Swift.String = Swift.String()

  /// Required. Mounted Image Age(in days).
  public var mountedImageAgeInDays: Swift.Int32 = Swift.Int32()

  /// Required. User Name.
  public var userName: Swift.String = Swift.String()

  /// Optional. Read Mode.
  public var readMode: Swift.String = Swift.String()

  /// Required. Resource size(in GiB)
  public var resourceSizeInGib: Swift.Double = Swift.Double()

  /// Optional. Image Expiration Date
  public var imageExpirationDate: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MountedImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MountedImage().with { $0.sourceResourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceResourceName = CodingKeys(stringValue: "sourceResourceName")
    static let sourceResourceId = CodingKeys(stringValue: "sourceResourceId")
    static let applianceName = CodingKeys(stringValue: "applianceName")
    static let applianceId = CodingKeys(stringValue: "applianceId")
    static let mountedImageName = CodingKeys(stringValue: "mountedImageName")
    static let sourceImageName = CodingKeys(stringValue: "sourceImageName")
    static let sourceImageType = CodingKeys(stringValue: "sourceImageType")
    static let recoveryPointDate = CodingKeys(stringValue: "recoveryPointDate")
    static let lastMountDate = CodingKeys(stringValue: "lastMountDate")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let sourceHostName = CodingKeys(stringValue: "sourceHostName")
    static let sourceHostId = CodingKeys(stringValue: "sourceHostId")
    static let mountedHostName = CodingKeys(stringValue: "mountedHostName")
    static let mountedHostId = CodingKeys(stringValue: "mountedHostId")
    static let mountedResourceName = CodingKeys(stringValue: "mountedResourceName")
    static let resourceVirtualSizeInGib = CodingKeys(stringValue: "resourceVirtualSizeInGib")
    static let storageConsumedInGib = CodingKeys(stringValue: "storageConsumedInGib")
    static let mountedResourceLabel = CodingKeys(stringValue: "mountedResourceLabel")
    static let restorableObject = CodingKeys(stringValue: "restorableObject")
    static let mountedImageAgeInDays = CodingKeys(stringValue: "mountedImageAgeInDays")
    static let userName = CodingKeys(stringValue: "userName")
    static let readMode = CodingKeys(stringValue: "readMode")
    static let resourceSizeInGib = CodingKeys(stringValue: "resourceSizeInGib")
    static let imageExpirationDate = CodingKeys(stringValue: "imageExpirationDate")

    static let _knownKeys: Set<Swift.String> = [
      "sourceResourceName",
      "sourceResourceId",
      "applianceName",
      "applianceId",
      "mountedImageName",
      "sourceImageName",
      "sourceImageType",
      "recoveryPointDate",
      "lastMountDate",
      "resourceType",
      "sourceHostName",
      "sourceHostId",
      "mountedHostName",
      "mountedHostId",
      "mountedResourceName",
      "resourceVirtualSizeInGib",
      "storageConsumedInGib",
      "mountedResourceLabel",
      "restorableObject",
      "mountedImageAgeInDays",
      "userName",
      "readMode",
      "resourceSizeInGib",
      "imageExpirationDate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceResourceName) {
      self.sourceResourceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceResourceId) {
      self.sourceResourceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceName) {
      self.applianceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceId) {
      self.applianceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountedImageName) {
      self.mountedImageName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceImageName) {
      self.sourceImageName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceImageType) {
      self.sourceImageType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recoveryPointDate) {
      self.recoveryPointDate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .lastMountDate) {
      self.lastMountDate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceHostName) {
      self.sourceHostName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceHostId) {
      self.sourceHostId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountedHostName) {
      self.mountedHostName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountedHostId) {
      self.mountedHostId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountedResourceName) {
      self.mountedResourceName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .resourceVirtualSizeInGib)
    {
      self.resourceVirtualSizeInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .storageConsumedInGib) {
      self.storageConsumedInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountedResourceLabel) {
      self.mountedResourceLabel = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .restorableObject) {
      self.restorableObject = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .mountedImageAgeInDays) {
      self.mountedImageAgeInDays = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userName) {
      self.userName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .readMode) {
      self.readMode = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .resourceSizeInGib) {
      self.resourceSizeInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageExpirationDate) {
      self.imageExpirationDate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceResourceName, forKey: .sourceResourceName)
    try container.encode(self.sourceResourceId, forKey: .sourceResourceId)
    try container.encode(self.applianceName, forKey: .applianceName)
    try container.encode(self.applianceId, forKey: .applianceId)
    try container.encode(self.mountedImageName, forKey: .mountedImageName)
    try container.encode(self.sourceImageName, forKey: .sourceImageName)
    try container.encode(self.sourceImageType, forKey: .sourceImageType)
    try container.encode(self.recoveryPointDate, forKey: .recoveryPointDate)
    try container.encode(self.lastMountDate, forKey: .lastMountDate)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.sourceHostName, forKey: .sourceHostName)
    try container.encode(self.sourceHostId, forKey: .sourceHostId)
    try container.encode(self.mountedHostName, forKey: .mountedHostName)
    try container.encode(self.mountedHostId, forKey: .mountedHostId)
    try container.encode(self.mountedResourceName, forKey: .mountedResourceName)
    try container.encode(self.resourceVirtualSizeInGib, forKey: .resourceVirtualSizeInGib)
    try container.encode(self.storageConsumedInGib, forKey: .storageConsumedInGib)
    try container.encode(self.mountedResourceLabel, forKey: .mountedResourceLabel)
    try container.encode(self.restorableObject, forKey: .restorableObject)
    try container.encode(self.mountedImageAgeInDays, forKey: .mountedImageAgeInDays)
    try container.encode(self.userName, forKey: .userName)
    try container.encode(self.readMode, forKey: .readMode)
    try container.encode(self.resourceSizeInGib, forKey: .resourceSizeInGib)
    try container.encode(self.imageExpirationDate, forKey: .imageExpirationDate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.MountedImage"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
