// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Holds information for the Mounted Images log
public struct MountedImage: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Source Resource name.
  public var sourceResourceName: Swift.String = Swift.String()

  /// Required. Source Resource id.
  public var sourceResourceId: Swift.String = Swift.String()

  /// Required. Cluster Name.
  public var applianceName: Swift.String = Swift.String()

  /// Required. Cluster Id.
  public var applianceId: Swift.String = Swift.String()

  /// Required. Mounted Image Name.
  public var mountedImageName: Swift.String = Swift.String()

  /// Required. Source Image Name.
  public var sourceImageName: Swift.String = Swift.String()

  /// Required.Source Image Type.
  public var sourceImageType: Swift.String = Swift.String()

  /// Required. Recovery point Date.
  public var recoveryPointDate: Swift.String = Swift.String()

  /// Required. Last Mount Date
  public var lastMountDate: Swift.String = Swift.String()

  /// Required. Resource type.
  public var resourceType: Swift.String = Swift.String()

  /// Required. Source Host Name.
  public var sourceHostName: Swift.String = Swift.String()

  /// Required. Source Host Id.
  public var sourceHostId: Swift.String = Swift.String()

  /// Required. Mounted Host Name.
  public var mountedHostName: Swift.String = Swift.String()

  /// Required. Mounted Host Id.
  public var mountedHostId: Swift.String = Swift.String()

  /// Required. Mounted Resource Name.
  public var mountedResourceName: Swift.String = Swift.String()

  /// Required. Resource Virtual size(in GiB)
  public var resourceVirtualSizeInGib: Swift.Double = Swift.Double()

  /// Required. Storage Consumed(in GiB).
  public var storageConsumedInGib: Swift.Double = Swift.Double()

  /// Optional. label.
  public var mountedResourceLabel: Swift.String = Swift.String()

  /// Optional. Restorable Objects.
  public var restorableObject: Swift.String = Swift.String()

  /// Required. Mounted Image Age(in days).
  public var mountedImageAgeInDays: Swift.Int32 = Swift.Int32()

  /// Required. User Name.
  public var userName: Swift.String = Swift.String()

  /// Optional. Read Mode.
  public var readMode: Swift.String = Swift.String()

  /// Required. Resource size(in GiB)
  public var resourceSizeInGib: Swift.Double = Swift.Double()

  /// Optional. Image Expiration Date
  public var imageExpirationDate: Swift.String = Swift.String()

  /// Initialize a new instance of `MountedImage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MountedImage().with { $0.sourceResourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.MountedImage"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
