// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Holds information for the Protected Resource
public struct ProtectedResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name.
  public var resourceName: Swift.String = Swift.String()

  /// Required. Resource Type.
  public var resourceType: Swift.String = Swift.String()

  /// Required. Resource ID.
  public var resourceId: Swift.String = Swift.String()

  /// Optional. Backup Inclusion/Exclusion.
  public var backupInclusionOrExclusion: Swift.String = Swift.String()

  /// Required. Host Id.
  public var hostId: Swift.String = Swift.String()

  /// Required. Host Name.
  public var hostName: Swift.String = Swift.String()

  /// Required. Backup Template ID.
  public var backupPlanPolicyTemplateId: Swift.String = Swift.String()

  /// Required. Backup Template.
  public var backupPlanPolicyTemplate: Swift.String = Swift.String()

  /// Required. Sla Id.
  public var slaId: Swift.String = Swift.String()

  /// Required. Backup Plan restrictions.
  public var backupPlanRestrictions: Swift.String = Swift.String()

  /// Required. Protected On.
  public var protectedOn: Swift.String = Swift.String()

  /// Optional. Policy Overrides.
  public var policyOverrides: Swift.String = Swift.String()

  /// Optional. Source Appliance in case of streamsnap.
  public var sourceAppliance: Swift.String = Swift.String()

  /// Optional. Source Appliance Id in case of streamsnap.
  public var sourceApplianceId: Swift.String = Swift.String()

  /// Required. Protected Data (GiB).
  public var protectedDataInGib: Swift.Double = Swift.Double()

  /// Optional. Onvault (GiB) .
  public var onvaultInGib: Swift.Double = Swift.Double()

  /// Optional. Originating Appliance in case of streamsnap.
  public var applianceName: Swift.String = Swift.String()

  /// Optional. Originating Appliance id in case of streamsnap.
  public var applianceId: Swift.String = Swift.String()

  /// Optional. Remote Appliance in case of streamsnap.
  public var remoteAppliance: Swift.String = Swift.String()

  /// Optional. Remote Appliance id in case of streamsnap.
  public var remoteApplianceId: Swift.String = Swift.String()

  /// Optional. Recovery Point.
  public var recoveryPoint: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProtectedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtectedResource().with { $0.resourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resourceName = CodingKeys(stringValue: "resourceName")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let resourceId = CodingKeys(stringValue: "resourceId")
    static let backupInclusionOrExclusion = CodingKeys(stringValue: "backupInclusionOrExclusion")
    static let hostId = CodingKeys(stringValue: "hostId")
    static let hostName = CodingKeys(stringValue: "hostName")
    static let backupPlanPolicyTemplateId = CodingKeys(stringValue: "backupPlanPolicyTemplateId")
    static let backupPlanPolicyTemplate = CodingKeys(stringValue: "backupPlanPolicyTemplate")
    static let slaId = CodingKeys(stringValue: "slaId")
    static let backupPlanRestrictions = CodingKeys(stringValue: "backupPlanRestrictions")
    static let protectedOn = CodingKeys(stringValue: "protectedOn")
    static let policyOverrides = CodingKeys(stringValue: "policyOverrides")
    static let sourceAppliance = CodingKeys(stringValue: "sourceAppliance")
    static let sourceApplianceId = CodingKeys(stringValue: "sourceApplianceId")
    static let protectedDataInGib = CodingKeys(stringValue: "protectedDataInGib")
    static let onvaultInGib = CodingKeys(stringValue: "onvaultInGib")
    static let applianceName = CodingKeys(stringValue: "applianceName")
    static let applianceId = CodingKeys(stringValue: "applianceId")
    static let remoteAppliance = CodingKeys(stringValue: "remoteAppliance")
    static let remoteApplianceId = CodingKeys(stringValue: "remoteApplianceId")
    static let recoveryPoint = CodingKeys(stringValue: "recoveryPoint")

    static let _knownKeys: Set<Swift.String> = [
      "resourceName",
      "resourceType",
      "resourceId",
      "backupInclusionOrExclusion",
      "hostId",
      "hostName",
      "backupPlanPolicyTemplateId",
      "backupPlanPolicyTemplate",
      "slaId",
      "backupPlanRestrictions",
      "protectedOn",
      "policyOverrides",
      "sourceAppliance",
      "sourceApplianceId",
      "protectedDataInGib",
      "onvaultInGib",
      "applianceName",
      "applianceId",
      "remoteAppliance",
      "remoteApplianceId",
      "recoveryPoint",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceName) {
      self.resourceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceId) {
      self.resourceId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupInclusionOrExclusion)
    {
      self.backupInclusionOrExclusion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostId) {
      self.hostId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostName) {
      self.hostName = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupPlanPolicyTemplateId)
    {
      self.backupPlanPolicyTemplateId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupPlanPolicyTemplate)
    {
      self.backupPlanPolicyTemplate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .slaId) {
      self.slaId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupPlanRestrictions)
    {
      self.backupPlanRestrictions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .protectedOn) {
      self.protectedOn = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policyOverrides) {
      self.policyOverrides = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceAppliance) {
      self.sourceAppliance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceApplianceId) {
      self.sourceApplianceId = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .protectedDataInGib) {
      self.protectedDataInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .onvaultInGib) {
      self.onvaultInGib = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceName) {
      self.applianceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceId) {
      self.applianceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remoteAppliance) {
      self.remoteAppliance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remoteApplianceId) {
      self.remoteApplianceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recoveryPoint) {
      self.recoveryPoint = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resourceName, forKey: .resourceName)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.resourceId, forKey: .resourceId)
    try container.encode(self.backupInclusionOrExclusion, forKey: .backupInclusionOrExclusion)
    try container.encode(self.hostId, forKey: .hostId)
    try container.encode(self.hostName, forKey: .hostName)
    try container.encode(self.backupPlanPolicyTemplateId, forKey: .backupPlanPolicyTemplateId)
    try container.encode(self.backupPlanPolicyTemplate, forKey: .backupPlanPolicyTemplate)
    try container.encode(self.slaId, forKey: .slaId)
    try container.encode(self.backupPlanRestrictions, forKey: .backupPlanRestrictions)
    try container.encode(self.protectedOn, forKey: .protectedOn)
    try container.encode(self.policyOverrides, forKey: .policyOverrides)
    try container.encode(self.sourceAppliance, forKey: .sourceAppliance)
    try container.encode(self.sourceApplianceId, forKey: .sourceApplianceId)
    try container.encode(self.protectedDataInGib, forKey: .protectedDataInGib)
    try container.encode(self.onvaultInGib, forKey: .onvaultInGib)
    try container.encode(self.applianceName, forKey: .applianceName)
    try container.encode(self.applianceId, forKey: .applianceId)
    try container.encode(self.remoteAppliance, forKey: .remoteAppliance)
    try container.encode(self.remoteApplianceId, forKey: .remoteApplianceId)
    try container.encode(self.recoveryPoint, forKey: .recoveryPoint)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.ProtectedResource"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
