// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Holds information for the Protected Resource
public struct ProtectedResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name.
  public var resourceName: Swift.String = Swift.String()

  /// Required. Resource Type.
  public var resourceType: Swift.String = Swift.String()

  /// Required. Resource ID.
  public var resourceId: Swift.String = Swift.String()

  /// Optional. Backup Inclusion/Exclusion.
  public var backupInclusionOrExclusion: Swift.String = Swift.String()

  /// Required. Host Id.
  public var hostId: Swift.String = Swift.String()

  /// Required. Host Name.
  public var hostName: Swift.String = Swift.String()

  /// Required. Backup Template ID.
  public var backupPlanPolicyTemplateId: Swift.String = Swift.String()

  /// Required. Backup Template.
  public var backupPlanPolicyTemplate: Swift.String = Swift.String()

  /// Required. Sla Id.
  public var slaId: Swift.String = Swift.String()

  /// Required. Backup Plan restrictions.
  public var backupPlanRestrictions: Swift.String = Swift.String()

  /// Required. Protected On.
  public var protectedOn: Swift.String = Swift.String()

  /// Optional. Policy Overrides.
  public var policyOverrides: Swift.String = Swift.String()

  /// Optional. Source Appliance in case of streamsnap.
  public var sourceAppliance: Swift.String = Swift.String()

  /// Optional. Source Appliance Id in case of streamsnap.
  public var sourceApplianceId: Swift.String = Swift.String()

  /// Required. Protected Data (GiB).
  public var protectedDataInGib: Swift.Double = Swift.Double()

  /// Optional. Onvault (GiB) .
  public var onvaultInGib: Swift.Double = Swift.Double()

  /// Optional. Originating Appliance in case of streamsnap.
  public var applianceName: Swift.String = Swift.String()

  /// Optional. Originating Appliance id in case of streamsnap.
  public var applianceId: Swift.String = Swift.String()

  /// Optional. Remote Appliance in case of streamsnap.
  public var remoteAppliance: Swift.String = Swift.String()

  /// Optional. Remote Appliance id in case of streamsnap.
  public var remoteApplianceId: Swift.String = Swift.String()

  /// Optional. Recovery Point.
  public var recoveryPoint: Swift.String = Swift.String()

  /// Initialize a new instance of `ProtectedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProtectedResource().with { $0.resourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.ProtectedResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
