// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This is a UnprotectedResourceLogReport published as part of GCBDR
/// Reporting.
public struct UnprotectedResourceReportLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the host where the application/resource resides.
  public var hostName: Swift.String = Swift.String()

  /// Required. Name of the application/resource.
  public var resourceName: Swift.String = Swift.String()

  /// Required. Type of the application/resource.
  public var resourceType: Swift.String = Swift.String()

  /// Optional. Name of the database instance for instance members.
  public var instanceName: Swift.String = Swift.String()

  /// Required. Date when the Appliance was Discovered first.
  public var discoveredOn: Swift.String = Swift.String()

  /// Required. Name of the appliance on which it was discovered.
  public var discoveredBy: Swift.String = Swift.String()

  /// Required. Id of the Appliance
  public var applianceId: Swift.String = Swift.String()

  /// Required. Id of the application/resource
  public var resourceId: Swift.String = Swift.String()

  /// Required. Id of the Host where the application/resource resides.
  public var hostId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `UnprotectedResourceReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UnprotectedResourceReportLog().with { $0.hostName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hostName = CodingKeys(stringValue: "hostName")
    static let resourceName = CodingKeys(stringValue: "resourceName")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let instanceName = CodingKeys(stringValue: "instanceName")
    static let discoveredOn = CodingKeys(stringValue: "discoveredOn")
    static let discoveredBy = CodingKeys(stringValue: "discoveredBy")
    static let applianceId = CodingKeys(stringValue: "applianceId")
    static let resourceId = CodingKeys(stringValue: "resourceId")
    static let hostId = CodingKeys(stringValue: "hostId")

    static let _knownKeys: Set<Swift.String> = [
      "hostName",
      "resourceName",
      "resourceType",
      "instanceName",
      "discoveredOn",
      "discoveredBy",
      "applianceId",
      "resourceId",
      "hostId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostName) {
      self.hostName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceName) {
      self.resourceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceName) {
      self.instanceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .discoveredOn) {
      self.discoveredOn = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .discoveredBy) {
      self.discoveredBy = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applianceId) {
      self.applianceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceId) {
      self.resourceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostId) {
      self.hostId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostName, forKey: .hostName)
    try container.encode(self.resourceName, forKey: .resourceName)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.instanceName, forKey: .instanceName)
    try container.encode(self.discoveredOn, forKey: .discoveredOn)
    try container.encode(self.discoveredBy, forKey: .discoveredBy)
    try container.encode(self.applianceId, forKey: .applianceId)
    try container.encode(self.resourceId, forKey: .resourceId)
    try container.encode(self.hostId, forKey: .hostId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.UnprotectedResourceReportLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
