// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// This is a UnprotectedResourceLogReport published as part of GCBDR
/// Reporting.
public struct UnprotectedResourceReportLog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the host where the application/resource resides.
  public var hostName: Swift.String = Swift.String()

  /// Required. Name of the application/resource.
  public var resourceName: Swift.String = Swift.String()

  /// Required. Type of the application/resource.
  public var resourceType: Swift.String = Swift.String()

  /// Optional. Name of the database instance for instance members.
  public var instanceName: Swift.String = Swift.String()

  /// Required. Date when the Appliance was Discovered first.
  public var discoveredOn: Swift.String = Swift.String()

  /// Required. Name of the appliance on which it was discovered.
  public var discoveredBy: Swift.String = Swift.String()

  /// Required. Id of the Appliance
  public var applianceId: Swift.String = Swift.String()

  /// Required. Id of the application/resource
  public var resourceId: Swift.String = Swift.String()

  /// Required. Id of the Host where the application/resource resides.
  public var hostId: Swift.String = Swift.String()

  /// Initialize a new instance of `UnprotectedResourceReportLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UnprotectedResourceReportLog().with { $0.hostName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.logging.v1.UnprotectedResourceReportLog"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
